services:
  - type: web
    name: fashionsmart-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python fastapi_api.py
    envVars:
      - key: PORT
        value: 5000